language: python
sudo: false

env:
  - LUA="lua 5.1"

before_install:
  - pip install hererocks
  - hererocks env --$LUA -rlatest    # Use latest LuaRocks, install into 'env' directory.
  - source env/bin/activate          # Add directory with all installed binaries to PATH.
  - luarocks install busted
  - luarocks install luacov

script:
  - busted
  - cat luacov.report.out

after_success:
  - bash <(curl -s https://codecov.io/bash)
